core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('store.urls', namespace='store')),
    path('basket/', include('store_basket.urls', namespace='store_basket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
   path('', views.product_all, name='product_all'),
   path('<slug:slug>', views.product_detail, name='product_detail'),
   path('shop/<slug:category_slug>', views.category_list, name='category_list')
]

store_basket/urls.py
from django.urls import path
from . import views

app_name = 'store_basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_delete', views.basket_delete, name='basket_delete'),
    path('basket_update', views.basket_update, name='basket_update')

]

store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser



# Create your models here.
class User(AbstractUser):
    def __str__(self):
        return self.username

class ProductManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)
        
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product',  on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images', default='images/default.jpg')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created  = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = ProductManager()
    objects = models.Manager()
    
    class Meta:
        verbose_name_plural = 'Products'
        ordering = ['created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

store_basket/models.py
from django.db import models

# Create your models here.

store/views.py
from django.shortcuts import render
from .models import Category, Product
from django.shortcuts import get_object_or_404
from django.db.models import Q


def product_all(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    products = Product.objects.filter(Q(category__name__icontains=q) | Q(title__icontains=q) | Q(description__icontains=q))
    return render(request, 'store/index.html', {'products':products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/product_detail.html', {'product':product})

def category_list(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/category.html', {'products':products, 'category':category})

store_basket/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .basket import Basket

from django.http import JsonResponse
from store.models import Product

# Create your views here.
def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store_basket/index.html', {"basket":basket})

def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        quantity = int(request.POST.get('quantity'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, quantity=quantity)

        basket_quantity = basket.__len__()
        response = JsonResponse({'quantity': basket_quantity})

        print(basket.basket)
        print(basket.basket.keys())
        print(basket.basket.values())
        
        return response

def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basket_qty = basket.__len__()
        basket_total = basket.get_total_price()
        response = JsonResponse({'subtotal':basket_total, 'qty':basket_qty})
        return response

def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_quantity = int(request.POST.get('productquantity'))
        basket.update(product=product_id, product_quantity=product_quantity)

        basket_qty = basket.__len__()
        basket_total = basket.get_total_price()
        
        response = JsonResponse({'qty':basket_qty, 'subtotal':basket_total})
        return response

store/templates/store/category.html
{% extends 'base.html' %}
{% block title %}{% if category %}{{category.name}}{% else %}Products{% endif %}{% endblock %}
{% block content %}


  <div class="album py-5 bg-light">
    <div class="container">

    <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img src="{{product.image.url}}" class="bd-placeholder-img card-img-top" width="100%" height="225" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <div class="card-body">
                <div class="card-header text-center">
                    <a class=" text-decoration-none" href="{{product.get_absolute_url}}"><h3>{{product.title}}</h3></a></div>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Price: {{product.price}}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
        
  </div>
  </div>
</div>

{% endblock %}

store/templates/store/index.html
{% extends 'base.html' %}
{% block title %}{% if product %}{{product.title}}{% else %}Products{% endif %}{% endblock %}
{% block content %}

<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img src="{{product.image.url}}" class="bd-placeholder-img card-img-top" width="100%" height="225" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <div class="card-body">
                <div class="card-header text-center">
                    <a class=" text-decoration-none" href="{{product.get_absolute_url}}"><h3>{{product.title}}</h3></a></div>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Price: {{product.price}}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
        
  </div>
  </div>
</div>


{% endblock %}

store/templates/store/product_detail.html
{% extends 'base.html' %}

{% block title %}{{product.title}}{% endblock %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
      <div class="row justify-content-center g-3">

        <div class="col col-auto col-sm-auto col-md-8 col-lg-7 col-xl-6">
            <div class="card shadow-sm">
              <img src="{{product.image.url}}" class="bd-placeholder-img card-img-top" width="100%" height="225" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
              <div class="card-body">
                  <div class="card-header text-center">
                      <a class=" text-decoration-none" href="{{product.get_absolute_url}}"><h3>{{product.title}}</h3></a></div>
                    <p><span class="lead">{{product.author|title}}</span> (Author)</p>
                <p class="card-text">{{product.description|slice:":355"}}</p>
              </div>
            </div>
          </div>

          <div class="row justify-content-center mt-3">
            <div class="col-md-6">
              <div class="card py-3">
                <div class="d-flex justify-content-center">
                  <small class="text-dark h4 text-end">Price: ${{product.price}}</small>
                  <div class="justify-content-center mx-2">
                    <label for="select">Qty</label>
                    <select id="select">
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                      <option>4</option>
                    </select>
                  </div>
                </div>
                <div class="d-flex justify-content-center">
<button id="add-button" value={{product.id}} class="btn btn-secondary btn">Add to Cart</button>
                </div>
              </div>
            </div>
          </div>
          </div>
        </div>
    </div>
    
<script>
    $(document).on('click', '#add-button', function (e) {
      e.preventDefault();
      $.ajax({
        type: 'POST',
        url: '{% url "store_basket:basket_add" %}',
        data: {
          productid: $('#add-button').val(),
          quantity: $('#select option:selected').text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function(json){
          document.getElementById("basket-qty").innerHTML = json.quantity
        },
        error: function (xhr, errmsg, err) {}
    });
  })
</script>


{% endblock %}

store_basket/templates/store_basket/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}

<main class="pt-5">
    <div class="container">
        <h1 class="h5">Shopping Cart</h1>
        {% for item in basket %}
        {% with product=item.product %}
        <div data-index="{{product.id}}" class="row mb-4 border product-item">
            <div class="col-md-3 col-lg-2 order-md-first bg-light">
                <img src="{{product.image.url}}" alt="" class="img-fluid mx-auto d-block">
            </div>
            <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                <a href="{{product.get_absolute_url}}" class="text-decoration-none text-reset"><h1 class="h5 pt-2">{{product.title}}</h1></a>
            <div class="border">
                <div class="col border-bottom">
                    <div class="row p-3">
                        <div class="col-6">Harback Book</div>
                        <div class="cosl-6 text-end"><span class="h6 fw-bold">{{product.price}}</span></div>
                        </div>
                        <div class="col">
                        <div class="row p-3">
                        <div class="col-12">
                            <label for="select">Quantity</label>
                            <select id="select{{product.id}}">
                                <option selected>{{item.quantity}}</option>
                                <option value="">1</option>
                                <option value="">2</option>
                                <option value="">3</option>
                                <option value="">4</option>
                            </select>
                            <button type="button" id="delete-button" data-index="{{product.id}}" class="btn btn-outline-secondary btn-sm delete-button">Delete</button>
                            <button type="button" id="update-button" class="btn btn-outline-secondary btn-sm update-button" data-index="{{product.id}}">Update</button>
                        </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}

        <div class="col-12 text-end">
        <div class="h6 fw-bold">Sub Total: $<span id="subtotal">{{basket.get_total_price}}</span>
        </div>
        </div>
    </div>
</main>

<script>
    $(document).on('click', '.delete-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "store_basket:basket_delete" %}',
        data: {
          productid: $(this).data('index'),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function(json){
            console.log(prodid)
            $('.product-item[data-index="'+ prodid +'"]').remove();
            document.getElementById("basket-qty").innerHTML = json.qty
            document.getElementById("subtotal").innerHTML = json.subtotal
        },
        error: function (xhr, errmsg, err) {}
    });
  })



    $(document).on('click', '.update-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "store_basket:basket_update" %}',
        data: {
          productid: $(this).data('index'),
          productquantity: $('#select' + prodid +' option:selected').text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function(json){
            document.getElementById("basket-qty").innerHTML = json.qty
            document.getElementById("subtotal").innerHTML = json.subtotal
        },
        error: function (xhr, errmsg, err) {}
    });
  })

</script>


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MySite - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/jquery-3.6.1.js' %}"></script>
</head>

{% include 'partials/_header.html'%}
<body>
    {% block content %}
    
    {% endblock %}
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    
</body>
</html>

templates/partials/_header.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'store:product_all' %}">MyShop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'store:product_all' %}">All</a></li>
                {% for c in categories %}
              <li {% if category.slug == c.slug %} class="bg-primary text-white"{% endif %}><a class="dropdown-item" href="{{c.get_absolute_url}}">{{c.name|title}}</a></li>
                {% endfor %}
            </ul>
          </li>
        </ul>
        <form class="d-flex" role="search" method="get">
          <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <div>
          <a href="{% url 'store_basket:basket_summary' %}" role="button" class="btn btn-primary mt-2 mt-md-0 ms-md-2 ">
            
            
            {% with total_quantity=basket|length %}
              {% if total_quantity > 0 %}
                <span id="basket-qty">{{total_quantity}}</span>
              {% else %}
                <span id="basket-qty">0</span>
              {% endif %}
            {% endwith %}
            
            
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4 ms-2" viewBox="0 0 16 16">
            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
          </svg> Cart</a>
        </div>
        
      </div>
      
    </div>
  </nav>